"""Initial migration

Revision ID: 1c883b65609c
Revises: 
Create Date: 2025-12-10 19:00:05.745022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c883b65609c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento_tipo',
    sa.Column('idTipoDocumento', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('idTipoDocumento')
    )
    op.create_table('empleado',
    sa.Column('id_empleados', sa.Integer(), nullable=False),
    sa.Column('nombre_empleado', sa.String(length=30), nullable=False),
    sa.Column('apellido_empleado', sa.String(length=30), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('tipo_documento', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('direccion', sa.String(length=45), nullable=True),
    sa.Column('cargo_establecido', sa.String(length=45), nullable=True),
    sa.Column('usuario', sa.String(length=15), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('temporal', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('email_confirmado', sa.Boolean(), nullable=True),
    sa.Column('token_confirmacion', sa.String(length=100), nullable=True),
    sa.Column('token_confirmacion_expiry', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('aceptado_terminos', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_empleados'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('numero_documento'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('inicio_de_sesion',
    sa.Column('userNumDoc', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('temporal', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('userNumDoc')
    )
    op.create_table('tanques',
    sa.Column('id_tanques', sa.Integer(), nullable=False),
    sa.Column('tipo_combustible', sa.String(length=45), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('altura_maxima_cm', sa.Float(), nullable=True),
    sa.Column('radio_cm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_tanques')
    )
    op.create_table('auditoria',
    sa.Column('id_auditoria', sa.Integer(), nullable=False),
    sa.Column('id_empleados', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=True),
    sa.Column('tabla', sa.String(length=50), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('datos_anteriores', sa.Text(), nullable=True),
    sa.Column('datos_nuevos', sa.Text(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['id_empleados'], ['empleado.id_empleados'], ),
    sa.PrimaryKeyConstraint('id_auditoria')
    )
    op.create_table('descargues',
    sa.Column('idDescargue', sa.Integer(), nullable=False),
    sa.Column('id_empleados', sa.Integer(), nullable=False),
    sa.Column('medida_inicial_cm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('medida_inicial_gl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descargue_cm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descargue_gl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('medida_final_cm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('medida_final_gl', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diferencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tanque', sa.String(length=50), nullable=True),
    sa.Column('observaciones1', sa.String(length=255), nullable=True),
    sa.Column('observaciones2', sa.String(length=255), nullable=True),
    sa.Column('kit_derrames', sa.String(length=5), nullable=True),
    sa.Column('extintores', sa.String(length=5), nullable=True),
    sa.Column('conos', sa.String(length=5), nullable=True),
    sa.Column('boquillas', sa.String(length=5), nullable=True),
    sa.Column('botas', sa.String(length=5), nullable=True),
    sa.Column('gafas', sa.String(length=5), nullable=True),
    sa.Column('tapaoidos', sa.String(length=5), nullable=True),
    sa.Column('guantes', sa.String(length=5), nullable=True),
    sa.Column('brillante', sa.String(length=5), nullable=True),
    sa.Column('traslucido', sa.String(length=5), nullable=True),
    sa.Column('claro', sa.String(length=5), nullable=True),
    sa.Column('solidos', sa.String(length=5), nullable=True),
    sa.Column('separacion', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('imagen_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_empleados'], ['empleado.id_empleados'], ),
    sa.PrimaryKeyConstraint('idDescargue')
    )
    op.create_table('inicio_de_sesion_has_empleado',
    sa.Column('id_empleados', sa.Integer(), nullable=False),
    sa.Column('userNumDoc', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_empleados'], ['empleado.id_empleados'], ),
    sa.ForeignKeyConstraint(['userNumDoc'], ['inicio_de_sesion.userNumDoc'], ),
    sa.PrimaryKeyConstraint('id_empleados', 'userNumDoc')
    )
    op.create_table('medicion_cargue',
    sa.Column('id_medicion_cargue', sa.Integer(), nullable=False),
    sa.Column('medida_anterior', sa.String(length=45), nullable=True),
    sa.Column('medida_posterior', sa.String(length=45), nullable=True),
    sa.Column('formato_de_entrega', sa.String(length=45), nullable=True),
    sa.Column('galones_totales', sa.String(length=45), nullable=True),
    sa.Column('id_tanques', sa.Integer(), nullable=True),
    sa.Column('id_empleados', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleados'], ['empleado.id_empleados'], ),
    sa.ForeignKeyConstraint(['id_tanques'], ['tanques.id_tanques'], ),
    sa.PrimaryKeyConstraint('id_medicion_cargue')
    )
    op.create_table('pedido_combustible',
    sa.Column('idPedido_Combustible', sa.Integer(), nullable=False),
    sa.Column('galones_acpm', sa.String(length=45), nullable=True),
    sa.Column('galones_corriente', sa.String(length=45), nullable=True),
    sa.Column('galones_extra', sa.String(length=45), nullable=True),
    sa.Column('total_galones', sa.String(length=45), nullable=True),
    sa.Column('id_empleados', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleados'], ['empleado.id_empleados'], ),
    sa.PrimaryKeyConstraint('idPedido_Combustible')
    )
    op.create_table('registro_medidas',
    sa.Column('id_registro_medidas', sa.Integer(), nullable=False),
    sa.Column('medida_combustible', sa.String(length=45), nullable=True),
    sa.Column('id_empleados', sa.Integer(), nullable=True),
    sa.Column('fecha_hora_registro', sa.DateTime(), nullable=True),
    sa.Column('galones', sa.Integer(), nullable=True),
    sa.Column('id_tanques', sa.Integer(), nullable=True),
    sa.Column('novedad', sa.String(length=255), nullable=True),
    sa.Column('tipo_medida', sa.String(length=30), nullable=True),
    sa.Column('imagen_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_empleados'], ['empleado.id_empleados'], ),
    sa.ForeignKeyConstraint(['id_tanques'], ['tanques.id_tanques'], ),
    sa.PrimaryKeyConstraint('id_registro_medidas')
    )
    op.create_table('sesiones_activas',
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_empleados', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_actividad', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleados'], ['empleado.id_empleados'], ),
    sa.PrimaryKeyConstraint('id_sesion'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('ventas',
    sa.Column('idVenta', sa.Integer(), nullable=False),
    sa.Column('id_tanques', sa.Integer(), nullable=True),
    sa.Column('cantidad_galones', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_tanques'], ['tanques.id_tanques'], ),
    sa.PrimaryKeyConstraint('idVenta')
    )
    op.create_table('documento',
    sa.Column('idDocumento', sa.Integer(), nullable=False),
    sa.Column('nombre_documento', sa.String(length=100), nullable=True),
    sa.Column('fecha_informe', sa.Date(), nullable=True),
    sa.Column('tipo_documento_informe', sa.String(length=45), nullable=True),
    sa.Column('tipo_medicion', sa.String(length=45), nullable=True),
    sa.Column('fecha_descargue', sa.Date(), nullable=True),
    sa.Column('id_empleado', sa.String(length=45), nullable=True),
    sa.Column('id_empleados', sa.Integer(), nullable=True),
    sa.Column('revision_vehiculo', sa.String(length=3), nullable=True),
    sa.Column('revision_conductor', sa.String(length=3), nullable=True),
    sa.Column('medida_inicial', sa.String(length=45), nullable=True),
    sa.Column('cantidad_descargue', sa.String(length=45), nullable=True),
    sa.Column('medida_final', sa.String(length=45), nullable=True),
    sa.Column('diferencias', sa.String(length=45), nullable=True),
    sa.Column('id_registro_medidas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleados'], ['empleado.id_empleados'], ),
    sa.ForeignKeyConstraint(['id_registro_medidas'], ['registro_medidas.id_registro_medidas'], ),
    sa.PrimaryKeyConstraint('idDocumento')
    )
    op.create_table('registro_medidas_has_medicion_cargue',
    sa.Column('id_registro_medidas', sa.Integer(), nullable=False),
    sa.Column('id_medicion_cargue', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medicion_cargue'], ['medicion_cargue.id_medicion_cargue'], ),
    sa.ForeignKeyConstraint(['id_registro_medidas'], ['registro_medidas.id_registro_medidas'], ),
    sa.PrimaryKeyConstraint('id_registro_medidas', 'id_medicion_cargue')
    )
    op.create_table('documento_adjunto',
    sa.Column('idAdjunto', sa.Integer(), nullable=False),
    sa.Column('idDocumento', sa.Integer(), nullable=True),
    sa.Column('nombre_archivo', sa.String(length=100), nullable=True),
    sa.Column('url_archivo', sa.Text(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idDocumento'], ['documento.idDocumento'], ),
    sa.PrimaryKeyConstraint('idAdjunto')
    )
    op.create_table('documento_historial',
    sa.Column('idHistorial', sa.Integer(), nullable=False),
    sa.Column('idDocumento', sa.Integer(), nullable=True),
    sa.Column('fecha_evento', sa.DateTime(), nullable=True),
    sa.Column('descripcion_evento', sa.String(length=255), nullable=True),
    sa.Column('usuario_responsable', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['idDocumento'], ['documento.idDocumento'], ),
    sa.PrimaryKeyConstraint('idHistorial')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documento_historial')
    op.drop_table('documento_adjunto')
    op.drop_table('registro_medidas_has_medicion_cargue')
    op.drop_table('documento')
    op.drop_table('ventas')
    op.drop_table('sesiones_activas')
    op.drop_table('registro_medidas')
    op.drop_table('pedido_combustible')
    op.drop_table('medicion_cargue')
    op.drop_table('inicio_de_sesion_has_empleado')
    op.drop_table('descargues')
    op.drop_table('auditoria')
    op.drop_table('tanques')
    op.drop_table('inicio_de_sesion')
    op.drop_table('empleado')
    op.drop_table('documento_tipo')
    # ### end Alembic commands ###
