"""Initial migration

Revision ID: 7abc27338ad7
Revises: 1c883b65609c
Create Date: 2025-12-10 19:03:02.832122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abc27338ad7'
down_revision = '1c883b65609c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
